import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";


export default function Home(props: { data: any; }) {
  const [data, setData] = useState(props.data);

  // function to reload the API after every call

  async function refresh() {
    const refreshedProps = await fetchData();
    setData(refreshedProps.data);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p className={styles.paragraph}>{data.slip.advice}</p>
        <button className={styles.button} onClick={refresh}>
          Seek Advice 🤲
        </button>
      </main>
    </>
  );
}

//fetching the data from API
async function fetchData() {
  const response = await fetch("https://api.adviceslip.com/advice");
  const data = await response.json();

  return { data };
}

Home.getInitialProps = fetchData;
